Cola_Prioridad.o: Cola_Prioridad.c
	gcc Cola_Prioridad.c -c
main.o: main.c
	gcc main.c -c

a.out: main.o Cola_Prioridad.o
	gcc main.o Cola_Prioridad.o

run: a.out
	./a.out

clean:
	rm -f a.out main.o Cola_Prioridad.o
