pilaarreglo.o: pilaarreglo.c
	gcc pilaarreglo -c
main.o: main.c
	gcc main.c -c

a.out: main.o pilaarreglo.o
	gcc main.o pilaarreglo.o

run: a.out
	./a.out

clean:
	rm -f a.out main.o pilaarreglo.o