listaDobleCircular.o: ListaDobleCircular.c
	gcc ListaDobleCircular.c -c
main.o: main.c
	gcc main.c -c

a.out: main.o ListaDobleCircular.o
	gcc main.o ListaDobleCircular.o

run: a.out
	./a.out

clean:
	rm -f a.out main.o ListaDobleCircular.o
